import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from "react";
import Sidebar, { SidebarSkeleton } from "@/components/sidebar/sidebar";
import { GeistSans } from 'geist/font/sans'
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "FormCraft | The best form builder for your website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={GeistSans.variable}>
      <body
        className={"bg-violet-200/40 text-primary"}
      >
        <Navbar />
        <div>
          <Suspense fallback={<SidebarSkeleton />}>
            <Sidebar sidebarPosition="left" />
          </Suspense>
          {children}
          <Suspense fallback={<SidebarSkeleton />}>
            <Sidebar sidebarPosition="right" />
          </Suspense>
        </div>
      </body>
    </html>
  );
}
